/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 camera-lense.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/camera-lense.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.33, -0.45, -0.82]} scale={11.5}>
        <mesh geometry={nodes.Mesh016.geometry} material={materials.Camera_01_lens_body} />
        <mesh geometry={nodes.Mesh016_3.geometry} material={materials.Camera_01_strap} />
      </group>
    </group>
  )
}

useGLTF.preload('/camera-lense.glb')
